# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataidea-R',
                'doc_host': 'https://dataideaorg.github.io',
                'git_url': 'https://github.com/dataideaorg/dataidea-R',
                'lib_path': 'dataidea_R'},
  'syms': {'dataidea_R.core': {'dataidea_R.core.foo': ('core.html#foo', 'dataidea_R/core.py')}}}
